// <auto-generated />
using System;
using System.Text.Json;
using MicroControllerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroControllerApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250907181849_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroControllerApi.Database.IotReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<JsonDocument>("Report")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("report");

                    b.HasKey("Id")
                        .HasName("pk_iot_reports");

                    b.ToTable("iot_reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
